# Generated by Django 3.1.1 on 2020-09-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_alert_alertlog_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="trigger_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
