# Generated by Django 3.1.1 on 2020-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0004_sensor_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
