# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PiHome application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements/dev.txt
    - name: Lint with blake
      run: black --diff --color ./ && black --check ./
    - name: Test
      run: cd server && coverage run manage.py test --settings=pihome_server.settings.ci
    - name: Coverage report
      run: cs server && coverage report -m
